services:
  redis:
    container_name: tareas-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - tareas-network

  postgres:
    container_name: tareas-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tareas
    networks:
      - tareas-network

  localstack:
    container_name: tareas-localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh

networks:
  tareas-network:
